apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-tick-tock-bong-deployment
  labels:
    app: go-tick-tock-bong
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-tick-tock-bong
  template:
    metadata:
      labels:
        app: go-tick-tock-bong
    spec:
      containers:
        - name: go-tick-tock-bong
          image: andres221293/go-tick-tock-bong:latest
          ports:
            - containerPort: 8080
