apiVersion: v1
kind: Service
metadata:
  name: go-tick-tock-bong-service
spec:
  type: LoadBalancer
  selector:
    app: go-tick-tock-bong
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
